# config_manual.yaml (Corrected and Updated)
version: 1.0.0

client:
  organization: org1
  logging:
    level: info
  cryptoconfig:
    path: ../../test-network/organizations
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    client:
      key:
        path: ../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: ../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt

channels:
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      # Added Peer 2
      peer2.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
      # Added Peer 2
      - peer2.org1.example.com

orderers:
  orderer.example.com:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: ../../test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

  peer1.org1.example.com:
    url: localhost:9051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt

  # Added Peer 2
  peer2.org1.example.com:
    url: localhost:9151
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt
