version: 1.0.0

client:
  organization: org1
  logging:
    level: info
  cryptoconfig:
    path: ../../test-network/organizations
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    client:
      key:
        path: ../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
      cert:
        path: ../../test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt

channels:
  mychannel:
    peers:
      # Define all peers from all orgs on the channel
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer2.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer2.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp
    peers:
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer2.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

  # Added Org2 definition
  org2:
    mspid: Org2MSP
    cryptoPath: peerOrganizations/org2.example.com/users/{username}@org2.example.com/msp
    peers:
      - peer0.org2.example.com
      - peer1.org2.example.com
      - peer2.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com

orderers:
  orderer.example.com:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: ../../test-network/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  # Org1 Peers
  peer0.org1.example.com:
    url: localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  peer1.org1.example.com:
    url: localhost:9051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
  peer2.org1.example.com:
    url: localhost:9151
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt

  # Added Org2 Peers
  peer0.org2.example.com:
    url: localhost:8100
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
  peer1.org2.example.com:
    url: localhost:8120
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/ca.crt
  peer2.org2.example.com:
    url: localhost:8140
    grpcOptions:
      ssl-target-name-override: peer2.org2.example.com
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org2.example.com/peers/peer2.org2.example.com/tls/ca.crt

# This section defines the CA certificates for MSP validation.
certificateAuthorities:
  ca.org1.example.com:
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org1.example.com/msp/cacerts/ca.org1.example.com-cert.pem
  # Added Org2 CA definition
  ca.org2.example.com:
    tlsCACerts:
      path: ../../test-network/organizations/peerOrganizations/org2.example.com/msp/cacerts/ca.org2.example.com-cert.pem
